# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Template
repo_url: 'https://github.com/autoresearch/autora-template'

nav:
- Home: 'index.md'
- Quickstart: 'quick_start_guide.md'
- Examples:
  - Basic Usage: 'basic_usage.ipynb'
  - Additional Example: 'additional_example.ipynb'
