on:
  workflow_dispatch
  
env:
  SRC_FILE: 'pyproject.toml'
  OUT_FILE_INDEX: 'docs/index.md'
  OUT_FILE_QUICK: 'docs/quick_start.md'
  BRANCH_NAME: build-pages-from-toml-$(date +%s)

jobs:
  build_pages_from_toml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Build pages
        id: build
        uses: younesStrittmatter/pages-from-pyproject-action@v1a0
        with:
          src-file: ${{ env.SRC_FILE }}
          out-file-index: ${{ env.OUT_FILE_INDEX }}
          out-file-quick: ${{ env.OUT_FILE_QUICK }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Create new branch
        run: |
          git checkout -b  ${{ env.BRANCH_NAME }}

      - name: Commit changes
        run: |
          git add ${{ env.OUT_FILE_INDEX }}
          git add ${{ env.OUT_FILE_QUICK }}
          git commit -m "Build pages using build-pages-from-toml.py"

      - name: Push changes to GitHub
        run: |
          git push origin HEAD

      - name: Create pull request
        run: |
          branch="${BRANCH_NAME}"
          echo "Creating pull request for branch: $branch"
          create-pull-request \
            --commit-message "Build pages using build-pages-from-toml.py" \
            --title "Build pages" \
            --body "Please review these changes." \
            --labels "auto-generated" \
            --reviewers "octocat" \
            --branch "$branch"
